apiVersion: v1
data:
  application-ccsm.yaml: |
    camunda:
      identity:
        clientId: "optimize"
        audience: "optimize-api"
        issuer: "https://normunda.de/auth/realms/camunda-platform"
        issuerBackendUrl: "http://camunda-keycloak:80/auth/realms/camunda-platform"
  environment-config.yaml: |
    container:
      contextPath: "/optimize"
    zeebe:
      enabled: false
      partitionCount: 9
      name: zeebe-record
    es:
      connection:
        nodes:
          - host: "camunda-elasticsearch"
            httpPort: 9200
    spring:
      profiles:
        active: "ccsm"
    security:
      auth:
        cookie:
          same-site:
            enabled: false
        ccsm:
          redirectRootUrl: "https://normunda.de/optimize"
    api:
      audience: "optimize-api"
      jwtSetUri: "http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/certs"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: camunda
    meta.helm.sh/release-namespace: camunda
  creationTimestamp: "2025-04-01T08:45:36Z"
  labels:
    app: camunda-platform
    app.kubernetes.io/component: optimize
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/version: 8.6.6
    helm.sh/chart: camunda-platform-11.2.2
  name: optimize-webapps-config
  namespace: camunda
  resourceVersion: "226490885"
  uid: 9714f7fa-8e61-4fe6-92a3-f6614a04d847
