# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml
# See options: https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/README.md

global:
  ingress:
    enabled: true
    className: nginx
    host: "normunda.de"
    tls:
      enabled: true
      secretName: "tls-secret"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-buffering: null
  identity:
    auth:
      publicIssuerUrl: "https://normunda.de/auth/realms/camunda-platform"
      issuerBackendUrl: "https://normunda.de/auth/realms/camunda-platform"
      operate:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/operate"
      tasklist:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/tasklist"
      optimize:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/optimize"
      zeebe:
        existingSecret:
          name: static-secret
      webModeler:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/modeler"

operate:
  contextPath: "/operate"

tasklist:
  contextPath: "/tasklist"

optimize:
  enabled: true
  contextPath: "/optimize"
  env:
    - name: OPTIMIZE_JAVA_OPTS
      value: "-Xmx2048m"
      # Runs every 5 minute in example
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_CRON_TRIGGER
      value: "*/5 * * * *"
      # Period of time zero days -> will clean up data immediately
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_TTL
      value: "P0D"
      # Will clean-up all processes
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_PROCESS_DATA_CLEANUP_CLEANUP_MODE
      value: "all"
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_PROCESS_DATA_CLEANUP_ENABLED
      value: "true"
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_DECISION_DATA_CLEANUP_ENABLED
      value: "true"
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_INGESTED_EVENT_CLEANUP_ENABLED
      value: "true"
    - name: CAMUNDA_OPTIMIZE_ZEEBE_INCLUDE_OBJECT_VARIABLE
      value: "false"


connectors:
  enabled: false
  contextPath: "/connectors"

identity:
  contextPath: "/identity"
  fullURL: "https://normunda.de/identity"

identityKeycloak:
  auth:
    adminPassword: EasySecret
    managementPassword: EasySecret
#  extraEnvVars:
#    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
#      value: "true"
#    - name: KEYCLOAK_FRONTEND_URL
#      value: "https://normunda.de/auth"

zeebeGateway:
  env:
    #- name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    #  value: "none"
    - name: CAMUNDA_REST_QUERY_ENABLED
      value: "true"
  ingress:
    grpc:
      enabled: true
      className: nginx
      host: "normunda.de"
      tls:
        enabled: true
        secretName: "tls-secret"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    rest:
      enabled: true
      path: "/zeebe"
      host: "normunda.de"
      tls:
        enabled: true
        secretName: "tls-secret"
  contextPath: "/zeebe"
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"

zeebe:
  # Test here
  annotations:
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: 'metrics/prometheus'
  clusterSize: 3
  partitionCount: 3
  replicationFactor: 3
  pvcSize: 10Gi

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"

webModeler:
  enabled: true
  contextPath: "/modeler"
  image:
    pullSecrets:
    # Create the secret as mentioned according to the instructions.
    - name: registry-camunda-cloud
  restapi:
    mail:
      smtpHost: smtp.example.com
      smtpPort: 587
      smtpUser: user
      smtpPassword: secret
      # Email address to be displayed as sender of emails from Web Modeler
      fromAddress: no-reply@example.com
    env:
      - name: LOGGING_LEVEL_IO_CAMUNDA_MODELER
        value: "Trace"
      - name: CAMUNDA_MODELER_CLUSTERS_0_ID
        value: "normunda-dev-1"
      - name: CAMUNDA_MODELER_CLUSTERS_0_NAME
        value: "normunda-dev"
      - name: CAMUNDA_MODELER_CLUSTERS_0_VERSION
        value: "8.6.1"
      - name: CAMUNDA_MODELER_CLUSTERS_0_AUTHENTICATION
        value: "OAUTH"
      - name: CAMUNDA_MODELER_CLUSTERS_0_URL_ZEEBE_GRPC
        value: "grpc://camunda-zeebe-gateway:26500"
      - name: CAMUNDA_MODELER_CLUSTERS_0_URL_ZEEBE_REST
        value: "http://camunda-zeebe-gateway:8080"
      - name: CAMUNDA_MODELER_CLUSTERS_0_URL_OPERATE
        value: "http://camunda-operate:80/operate"
      - name: CAMUNDA_MODELER_CLUSTERS_0_URL_TASKLIST
        value: "http://camunda-tasklist:80/tasklist"
      - name: CAMUNDA_MODELER_CLUSTERS_0_OAUTH_URL
        value: "http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token"
      - name: CAMUNDA_MODELER_CLUSTERS_0_OAUTH_AUDIENCE_ZEEBE
        value: "zeebe-api"
      - name: CAMUNDA_MODELER_CLUSTERS_0_OAUTH_AUDIENCE_OPERATE
        value: "operate-api"
      - name: CAMUNDA_MODELER_CLUSTERS_0_OAUTH_AUDIENCE_TASKLIST
        value: "tasklist-api"
postgresql:
  enabled: true

elasticsearch:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: default
      interval: 10s
      scrapeTimeout: 10s
  master:
    replicaCount: 1
  global:
    kibanaEnabled: true
  kibana:
    #image:
    #  tag: 8.9.2
    ingress:
      tls: true
      enabled: true
      ingressClassName: nginx
      hostname: "normunda.de"
      path: "/kibana"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
    configuration:
      server:
        basePath: "/kibana"
        rewriteBasePath: true
    readinessProbe:
      enabled: false

  #initScripts:
    #init-keystore.sh: |
    #  #!/bin/bash
    #  set -e#

#      echo "Adding S3 access keys to Elasticsearch keystore..."

      # Add S3 client default keys to the keystore
 #     echo "$S3_SECRET_KEY" | elasticsearch-keystore add -f -x s3.client.default.secret_key
  #    echo "$S3_ACCESS_KEY" | elasticsearch-keystore add -f -x s3.client.default.access_key

  extraEnvVars:
    - name: S3_SECRET_KEY
      value: minioadmin
    - name: S3_ACCESS_KEY
      value: minioadmin

prometheusServiceMonitor:
  enabled: true