# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml
# See options: https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/README.md

# helm install --version 11.2.2 --namespace camunda --create-namespace camunda camunda/camunda-platform -f 8.6-with-mt-values.yaml
global:
  license:
    existingSecret: "camunda-license"
    existingSecretKey: "key"
  multitenancy:
    enabled: true
  ingress:
    enabled: true
    className: nginx
    host: "normunda.de"
    tls:
      enabled: true
      secretName: "tls-secret"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      # Testing because of redirect errors
      # Can be refined, and maybe declare dedicated Operate ingress?
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "route"
      nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
  identity:
    auth:
      publicIssuerUrl: "https://normunda.de/auth/realms/camunda-platform"
      operate:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/operate"
      tasklist:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/tasklist"
      optimize:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/optimize"
      connectors:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/connectors"
      zeebe:
        existingSecret:
          name: static-secret
      webModeler:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/modeler"

operate:
  enabled: true
  contextPath: "/operate"
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi
  retention:
    enabled: true
    minimumAge: 30d
  env:
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFREPLICAS
      value: "2" # resilient ES
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFSHARDS
      value: "3" # performant ES

tasklist:
  enabled: true
  contextPath: "/tasklist"
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi
  retention:
    enabled: true
    minimumAge: 30d
  env:
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_NUMBEROFREPLICAS
      value: "2" # resilient ES
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_NUMBEROFSHARDS
      value: "3" # performant ES

optimize:
  enabled: true
  contextPath: "/optimize"
  # TODO: Needs to be adjusted to Zeebe partitionCount
  partitionCount: "9"
  env:
    - name: OPTIMIZE_JAVA_OPTS
      value: "-Xmx2048m"
      # Runs every 5 minute in example
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_CRON_TRIGGER
      value: "*/5 * * * *"
      # Period of time zero days -> will clean up data immediately
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_TTL
      value: "P7D"
      # Will clean-up all processes
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_PROCESS_DATA_CLEANUP_CLEANUP_MODE
      value: "all"
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_PROCESS_DATA_CLEANUP_ENABLED
      value: "true"
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_DECISION_DATA_CLEANUP_ENABLED
      value: "true"
    - name: CAMUNDA_OPTIMIZE_HISTORY_CLEANUP_INGESTED_EVENT_CLEANUP_ENABLED
      value: "true"
    - name: CAMUNDA_OPTIMIZE_ZEEBE_INCLUDE_OBJECT_VARIABLE
      value: "false"
    - name: MULTITENANCY_ENABLED
      value: "true"

connectors:
  enabled: true
  replicas: 3
  contextPath: "/connectors"
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

console:
  enabled: false

identity:
  contextPath: "/identity"
  fullURL: "https://normunda.de/identity"
  externalDatabase:
    enabled: true
    database: camunda
    host: my-postgresql.camunda.svc.cluster.local
    port: 5432
    username: camunda
    password: camunda
  resources:
    limits: null
    requests:
      cpu: 1
      memory: 1Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - identity
          topologyKey: "kubernetes.io/hostname"  # Ensure this is correctly indented and formatted

identityKeycloak:
  enabled: true
  replicaCount: 3
  postgresql:
    enabled: false
  externalDatabase:
    enabled: true
    database: camunda
    host: my-postgresql.camunda.svc.cluster.local
    port: 5432
    user: camunda
    password: camunda
  auth:
    adminPassword: EasySecret
    managementPassword: EasySecret
  extraEnvVars:
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_FRONTEND_URL
      value: "https://normunda.de/auth"
    - name: KC_DB_SCHEMA
      value: "keycloak"
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 2
      memory: 1Gi

identityPostgresql:
  enabled: false

zeebeGateway:
  replicas: 3
  ingress:
    grpc:
      enabled: true
      className: nginx
      host: "normunda.de"
      tls:
        enabled: true
        secretName: "tls-secret"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    rest:
      enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: 1
    limits: null
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true" # monitoring
    - name: ZEEBE_GATEWAY_THREADS_GRPCMAXTHREADS
      value: "50" # multi-tenancy performance
    #- name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    #  value: "none"

zeebe:
  clusterSize: "3"
  partitionCount: "9"
  replicationFactor: "3"
  pvcSize: 20Gi
  resources:
    requests:
      cpu: 1
      memory: 5Gi
    limits:
      cpu: null
      memory: 64Gi
  retention:
    enabled: true
    minimumAge: 7d
  env:
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_NUMBEROFREPLICAS
      value: "2" # resilient ES
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_NUMBEROFSHARDS
      value: "3" # performant ES

webModeler:
  enabled: true
  contextPath: "/modeler"
  image:
    pullSecrets:
      # Create the secret as mentioned according to the instructions.
      - name: registry-camunda-cloud
  restapi:
    mail:
      smtpHost: smtp.example.com
      smtpPort: 587
      smtpUser: user
      smtpPassword: secret
      # Email address to be displayed as sender of emails from Web Modeler
      fromAddress: no-reply@example.com
    env:
      - name: LOGGING_LEVEL_IO_CAMUNDA_MODELER
        value: "Trace"
      - name: CAMUNDA_MODELER_CLUSTERS_0_ID
        value: "normunda-dev-1"
      - name: CAMUNDA_MODELER_CLUSTERS_0_NAME
        value: "normunda-dev"
      - name: CAMUNDA_MODELER_CLUSTERS_0_VERSION
        value: "8.6.1"
      - name: CAMUNDA_MODELER_CLUSTERS_0_AUTHENTICATION
        value: "OAUTH"
      - name: CAMUNDA_MODELER_CLUSTERS_0_URL_ZEEBE_GRPC
        value: "grpc://camunda-zeebe-gateway:26500"
      - name: CAMUNDA_MODELER_CLUSTERS_0_URL_ZEEBE_REST
        value: "http://camunda-zeebe-gateway:8080"
      - name: CAMUNDA_MODELER_CLUSTERS_0_URL_OPERATE
        value: "http://camunda-operate:80/operate"
      - name: CAMUNDA_MODELER_CLUSTERS_0_URL_TASKLIST
        value: "http://camunda-tasklist:80/tasklist"
      - name: CAMUNDA_MODELER_CLUSTERS_0_OAUTH_URL
        value: "http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token"
      - name: CAMUNDA_MODELER_CLUSTERS_0_OAUTH_AUDIENCE_ZEEBE
        value: "zeebe-api"
      - name: CAMUNDA_MODELER_CLUSTERS_0_OAUTH_AUDIENCE_OPERATE
        value: "operate-api"
      - name: CAMUNDA_MODELER_CLUSTERS_0_OAUTH_AUDIENCE_TASKLIST
        value: "tasklist-api"
postgresql:
  enabled: true
  auth:
    existingSecret: static-secret

elasticsearch:
  resources:
    limits:
      cpu: 8
      memory: 64Gi
    requests:
      cpu: 4
      memory: 8Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: default
      interval: 10s
      scrapeTimeout: 10s
  master:
    replicaCount: 3
    podAntiAffinityPreset: hard
    env:
      - name: cluster.routing.allocation.awareness.attributes
        value: "failure-domain.beta.kubernetes.io/zone"
  data:
    replicaCount: 3
    env:
      - name: "cluster.routing.allocation.awareness.attributes"
        value: "zone"
  global:
    kibanaEnabled: true
  kibana:
    ingress:
      tls: true
      enabled: true
      ingressClassName: nginx
      hostname: "normunda.de"
      path: "/kibana"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
    configuration:
      server:
        basePath: "/kibana"
        rewriteBasePath: true
    readinessProbe:
      enabled: false

prometheusServiceMonitor:
  enabled: true