# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml
# See options: https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/README.md

global:
  ingress:
    enabled: true
    className: nginx
    host: "normunda.de"
    tls:
      enabled: true
      secretName: "tls-secret"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  identity:
    auth:
      publicIssuerUrl: "https://normunda.de/auth/realms/camunda-platform"
      operate:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/operate"
      tasklist:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/tasklist"
      optimize:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/optimize"
      connectors:
        existingSecret:
          name: static-secret
        redirectUrl: "https://normunda.de/connectors"
      zeebe:
        existingSecret:
          name: static-secret

operate:
  enabled: true
  contextPath: "/operate"
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi
  retention:
    enabled: true
    minimumAge: 30d
  env:
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFREPLICAS
      value: "3" # resilient ES
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFSHARDS
      value: "3" # performant ES

tasklist:
  enabled: true
  contextPath: "/tasklist"
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi
  retention:
    enabled: true
    minimumAge: 30d
  env:
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_NUMBEROFREPLICAS
      value: "3" # resilient ES
    - name: CAMUNDA_TASKLIST_ELASTICSEARCH_NUMBEROFSHARDS
      value: "3" # performant ES

optimize:
  enabled: false

connectors:
  enabled: true
  replicas: 3
  contextPath: "/connectors"
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

console:
  enabled: false

identity:
  contextPath: "/identity"
  fullURL: "https://normunda.de/identity"
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi

identityKeycloak:
  enabled: true
  replicaCount: 3
  auth:
    adminPassword: EasySecret
    managementPassword: EasySecret
  extraEnvVars:
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_FRONTEND_URL
      value: "https://normunda.de/auth"
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 2
      memory: 1Gi

identityPostgresql:
  enabled: true

zeebeGateway:
  replicas: 3
  ingress:
    grpc:
      enabled: true
      className: nginx
      host: "normunda.de"
      tls:
        enabled: true
        secretName: "tls-secret"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    rest:
      enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: 1
    limits: null
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true" # monitoring
    - name: ZEEBE_GATEWAY_THREADS_GRPCMAXTHREADS
      value: "50" # multi-tenancy performance
    - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
      value: "none"

zeebe:
  clusterSize: "12"
  partitionCount: "12"
  replicationFactor: "3"
  pvcSize: 20Gi
  resources:
    requests:
      cpu: 1
      memory: 5Gi
    limits:
      cpu: null
      memory: 64Gi
  retention:
    enabled: true
    minimumAge: 7d
  env:
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_NUMBEROFREPLICAS
      value: "3" # resilient ES
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_NUMBEROFSHARDS
      value: "3" # performant ES

elasticsearch:
  enabled: true
  master:
    masterOnly: FALSE
    heapSize: 4092m
    replicaCount: 1
    resources:
      limits:
        cpu: 8
        memory: 64Gi
      requests:
        cpu: 4
        memory: 8Gi
  global:
    kibanaEnabled: true
  kibana:
    #image:
    #  tag: 8.9.2
    ingress:
      tls: true
      enabled: true
      ingressClassName: nginx
      hostname: "normunda.de"
      path: "/kibana"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.kubernetes.io/rewrite-target: "/"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
    configuration:
      server:
        basePath: "/kibana"
        rewriteBasePath: true
    readinessProbe:
      enabled: false

prometheusServiceMonitor:
  enabled: true