auth:
  rootUser: minioadmin
  rootPassword: minioadmin

defaultBuckets: zeebe-backup,operate-backup,tasklist-backup

ingress:
  enabled: false
  hostname: "minio.normunda.de"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  ingressClassName: nginx

persistence:
  size: 10Gi