auth:
  rootUser: minioadmin
  rootPassword: minioadmin

defaultBuckets: zeebe-backup,operate-backup,tasklist-backup

ingress:
  enabled: true
  hostname: "normunda.de"
  tls: true
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  ingressClassName: nginx