apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-job
  labels:
    app: benchmark
spec:
  activeDeadlineSeconds: 1200
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
        - name: benchmark
          image: europe-central2-docker.pkg.dev/normunda/normansbenchmarkingtest/c8bmt:v1.0
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTIONS
              value: >-
                -Dzeebe.client.cloud.clientId=zeebe
                -Dzeebe.client.cloud.clientSecret=XjaV2e3w8EbJkHTq
                -Dzeebe.client.cloud.authUrl=http://camunda-keycloak/auth/realms/camunda-platform/protocol/openid-connect/token
                -Dzeebe.client.broker.grpcAddress=grpc://camunda-zeebe-gateway:26500
                -Dzeebe.client.security.plaintext=true
                -Dzeebe.client.request-timeout=600s
                -Dzeebe.client.job.poll-interval=1ms
                -Dzeebe.client.default-job-worker-stream-enabled=true
                -Dbenchmark.startPiPerSecond=5
                -Dbenchmark.startPiIncreaseFactor=0.4
                -Dbenchmark.startRateAdjustmentStrategy=none
                -Dbenchmark.fixedBackOffDelay=0
                -Dbenchmark.maxBackpressurePercentage=10.0
                -Dbenchmark.taskCompletionDelay=20
                -Dbenchmark.bpmnResource=classpath:bpmn/typical_process_straightthrough.bpmn
                -Dbenchmark.bpmnProcessId=straightthrough
                -Dbenchmark.payloadPath=file:/config/typical_payload.json
                -Dbenchmark.autoDeployProcess=true
                -Dbenchmark.warmupPhaseDurationMillis=60000
                -Dzeebe.client.worker.max-jobs-active=1000
                -Dzeebe.client.worker.threads=50
                -Dbenchmark.multiTenancyEnabled=true
                -Dbenchmark.tenantIds=<default>,test,norman
          resources:
            limits:
              cpu: 3
              memory: 4Gi
            requests:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: payload
              mountPath: /config
              readOnly: true
      volumes:
        - name: payload
          configMap:
            name: payload
      restartPolicy: Never
  backoffLimit: 4