apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: normanstest
  region: eu-central-1 
  version: "1.28"

managedNodeGroups:
  - name: ng-1
    instanceType: c6i.4xlarge
    desiredCapacity: 3
    minSize: 1
    maxSize: 6
    volumeSize: 
    privateNetworking: true

availabilityZones: ['eu-central-1a', 'eu-central-1b']
