---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
#provisioner: kubernetes.io/aws-ebs
provisioner: ebs.csi.aws.com
# parameters:
#   type: gp3
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
