name: Convert Markdown to PDF and Push Changes

on:
  push:
    branches:
      - main  # Runs the workflow when pushing to the main branch

jobs:
  convert_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Pandoc and LaTeX (required for converting Markdown to PDF)
      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive-latex-base texlive-latex-extra

      # Step 3: Convert Markdown to PDF
      - name: Convert Markdown to PDF
        run: |
          pandoc google/normunda/HA-WebApps/README.md -o google/normunda/HA-WebApps/pdf/instructions.pdf

      # Step 4: Commit and Push PDF file using GITHUB_TOKEN
      - name: Commit and Push PDF file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add google/normunda/HA-WebApps/pdf/instructions.pdf
          git commit -m 'Automatically converted Markdown to PDF' || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Belike/C8_Values.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
